version: "3"
services:
  app:
    env_file:
      - .env
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - borsch-playground-network
networks:
  borsch-playground-network:
    external: true
